// google fonts
import { Quicksand, Merriweather } from "next/font/google";

// css
import "./globals.css";

// components
import MainHeader from "@/components/layout/MainHeader";
import Footer from "@/components/layout/Footer";
import PageBackground from "@/components/layout/PageBackground";

const quicksand = Quicksand({
	variable: "--font-quicksand-sans",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"]
});

const merriweather = Merriweather({
	variable: "--font-merriweather",
	subsets: ["latin"],
	weight: ["300", "400", "700", "900"]
});

// TODO: what metadata should i include?
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${quicksand.className} antialiased min-h-screen relative xl:px-48 2xl:px-96`}>
				<PageBackground />
				<div className="relative">
					<MainHeader />
					<main className="grid opacity-100 place-content-center text-center gap-6 sm:gap-12 md:gap-20 p-6 sm:p-12 md:p-24 pt-24 sm:pt-24 md:pt-48 sm:text-xl md:text-2xl">
						{children}
					</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
