// google fonts
import { Quicksand, Merriweather } from "next/font/google";

// css
import "./globals.css";

// components
import MainHeader from "@/components/layout/MainHeader";
import Footer from "@/components/layout/Footer";
import PageBackground from "@/components/layout/PageBackground";

const quicksand = Quicksand({
	variable: "--font-quicksand-sans",
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"]
});

const merriweather = Merriweather({
	variable: "--font-merriweather",
	subsets: ["latin"],
	weight: ["300", "400", "700", "900"]
});

// TODO: what metadata should i include?
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${quicksand.className} antialiased min-h-screen relative`}>
				<PageBackground />
				<div className="relative z-10">
					<MainHeader />
					<main className="grid opacity-100">
						<div className="mt-16">{children}</div>
					</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
